### ISSUE TITLE
Use the template to set up a temporary landing page for http://www.lancealot.me/ and http://www.lancealotapp.com/ 

### ISSUE THREAD

**Issue by arturo-mayorga** [arturo-mayorga/e1e7ead4ddcae1e57e282c5dc5f37787#2]
Use the template to set up a temporary landing page for http://www.lancealot.me/ and http://www.lancealotapp.com/ 
* I recommend using an early version of the template.
*  Include the textual description
* Leave the video for latter
* Leave the signup functionality for latter

**Comment by juliamcinnis** [comment]
All sounds good. Here's the additional text for the homepage:
"Lancealot was created by filmmakers, artists, and entrepreneurs who want to help content creators build exciting and long-lasting careers. We're based in Chicago and NYC, but our freelancers are all over the world."

**Comment by arturo-mayorga** [comment]
Reopening, this is not yet completed.
